1. 다음 두 배열을 만든 후, 덧셈 연산을 한 뒤, 결과를 출력하는 스크립트를 작성해보세요.

In [4]:
import numpy as np

arr1 = np.array([[1,2],[3,4],[5,6]])
arr2 = np.array([[6,5],[4,3],[2,1]])
res = arr1+arr2

print(arr1)
print(arr2)
print(res)

[[1 2]
 [3 4]
 [5 6]]
[[6 5]
 [4 3]
 [2 1]]
[[7 7]
 [7 7]
 [7 7]]


2. NumPy 배열로 다음 배열을 만든 다음

In [5]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2-1. 두 번째 행에서 첫 번쨰, 세 번째 값만 추출하는 스크립트를 작성해보세요.

In [6]:
print(arr[1,0])
print(arr[1,2])

5
7


2-2. 빨간색 원소만 출력하는 스크립트를 작성해보세요.

In [13]:
print(arr[1:3,2:4])

[[ 7  8]
 [11 12]]


2-3. 모든 행을 거꾸로 출력하는 스크립트를 작성해보세요.

In [15]:
print(arr[::-1,:])

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


2-4. 모든 열을 거꾸로 출력하는 스크립트를 작성해보세요.

In [16]:
print(arr[:,::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
